# ===============================
# Application
# ===============================
spring.application.name=demo

# ===============================
# MySQL Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:{add your port and db name]
spring.datasource.username=your db username}
spring.datasource.password={your db pass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.security.user.name={setup custom sec username or remove line this and line 14 and spring generates in console}
spring.security.user.password={you can set a default pass for spring security or diable it and spring will generate one for you}
# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

stripe.secret.key={ADD YOUR KEY}
stripe.webhook.secret={ADD YOUR WEBHOOK SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username={YOUR EMAIL}
spring.mail.password={YOUR EMAIL APP PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional (Hibernate usually detects this automatically)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# Server
# ===============================
server.port=8080